import http from "node:http";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { Readable } from "node:stream";
import {
  applyDefaultEffort,
  approxTokenCount,
  extractInstructionsFromSystem,
  mapResponsesOutputToAnthropicContent,
  sanitizeToolFields,
  sanitizeUnsupportedRequestFields,
  toResponsesInput,
} from "./anthropic-responses.ts";
import {
  mapAnthropicToolChoiceToResponsesToolChoice,
  mapAnthropicToolsToResponsesTools,
} from "./tool-schema.ts";
import type { JsonObject } from "./types.ts";
import { type AuthState, buildUpstreamUrl, mergeRequestHeaders, rewriteRequestPath } from "./upstream.ts";

export interface ProxyOptions {
  forcedModel: string;
  defaultReasoningEffort: string;
  preserveClientEffort: boolean;
  debug: boolean;
  safeMode: boolean;
  workspaceSummary?: string;
  upstreamWireApi: "messages" | "responses";
}

function writeJson(res: http.ServerResponse, statusCode: number, data: unknown): void {
  const body = JSON.stringify(data);
  res.writeHead(statusCode, {
    "content-type": "application/json",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

function readBody(req: http.IncomingMessage): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer | string) => {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

function copyHeadersFromUpstream(headers: Headers): Record<string, string> {
  const out: Record<string, string> = {};
  headers.forEach((value, key) => {
    const normalized = key.toLowerCase();
    if (
      normalized === "transfer-encoding" ||
      normalized === "content-encoding" ||
      normalized === "content-length"
    ) {
      return;
    }
    out[key] = value;
  });
  return out;
}

function appendWorkspaceSummaryIfNeeded(
  parsed: JsonObject,
  filteredTools: Array<Record<string, unknown>>,
  workspaceSummary?: string
): void {
  if (filteredTools.length > 0 || !workspaceSummary || workspaceSummary.length === 0) {
    return;
  }
  const existingInstructions = typeof parsed.instructions === "string" ? parsed.instructions : "";
  parsed.instructions = `${existingInstructions}\n\nLocal workspace snapshot (autogenerated):\n${workspaceSummary}\n\nWhen asked about this folder/project, answer concretely and immediately from this snapshot. Do not say you will inspect or check files. Do not ask for extra time before answering.`.trim();
}

function adaptAnthropicMessagesRequestForResponses(parsed: JsonObject, options: ProxyOptions): JsonObject {
  if (typeof parsed.instructions !== "string") {
    const instructions = extractInstructionsFromSystem(parsed.system);
    if (instructions) {
      parsed.instructions = instructions;
    }
  }

  parsed.input = toResponsesInput(parsed.messages);

  const mappedTools = mapAnthropicToolsToResponsesTools(parsed.tools);
  const filteredTools = options.safeMode
    ? mappedTools.filter((tool) => String(tool.name || "").trim().toLowerCase() !== "toolsearch")
    : mappedTools;
  appendWorkspaceSummaryIfNeeded(parsed, filteredTools, options.workspaceSummary);
  parsed.tools = filteredTools.length > 0 ? filteredTools : undefined;

  const mappedToolChoice = mapAnthropicToolChoiceToResponsesToolChoice(parsed.tool_choice);
  if (mappedToolChoice !== undefined) {
    parsed.tool_choice = mappedToolChoice;
  } else {
    delete parsed.tool_choice;
  }

  const effort = parsed.output_config?.effort ?? parsed.reasoning?.effort;
  if (typeof effort === "string" && effort.length > 0) {
    parsed.reasoning = {
      ...(parsed.reasoning && typeof parsed.reasoning === "object" ? parsed.reasoning : {}),
      effort,
    };
  }

  delete parsed.messages;
  delete parsed.system;
  delete parsed.max_tokens;
  delete parsed.max_output_tokens;
  delete parsed.output_config;
  delete parsed.thinking;
  delete parsed.metadata;
  parsed.store = false;
  return parsed;
}

function writeSseEvent(res: http.ServerResponse, event: string, data: unknown): void {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

function parseSseEvents(buffered: string, handler: (eventName: string, data: any) => void): string {
  let working = buffered.replace(/\r\n/g, "\n");
  let boundary = working.indexOf("\n\n");

  while (boundary !== -1) {
    const rawEvent = working.slice(0, boundary);
    working = working.slice(boundary + 2);

    let eventName = "";
    let dataText = "";
    for (const line of rawEvent.split("\n")) {
      if (line.startsWith("event:")) {
        eventName = line.slice(6).trim();
      } else if (line.startsWith("data:")) {
        dataText += line.slice(5).trim();
      }
    }

    if (eventName && dataText) {
      try {
        handler(eventName, JSON.parse(dataText));
      } catch {
        /* ignore malformed events */
      }
    }

    boundary = working.indexOf("\n\n");
  }

  return working;
}

function persistRefreshedChatgptTokens(
  authPath: string,
  refreshed: {
    accessToken: string;
    idToken?: string;
    refreshToken?: string;
  },
  debug: boolean
): void {
  try {
    const current = existsSync(authPath) ? readFileSync(authPath, "utf8") : "{}";
    const parsed = JSON.parse(current) as Record<string, any>;
    if (!parsed.tokens || typeof parsed.tokens !== "object") {
      parsed.tokens = {};
    }

    parsed.tokens.access_token = refreshed.accessToken;
    if (typeof refreshed.idToken === "string" && refreshed.idToken.length > 0) {
      parsed.tokens.id_token = refreshed.idToken;
    }
    if (typeof refreshed.refreshToken === "string" && refreshed.refreshToken.length > 0) {
      parsed.tokens.refresh_token = refreshed.refreshToken;
    }
    parsed.last_refresh = new Date().toISOString();

    writeFileSync(authPath, `${JSON.stringify(parsed, null, 2)}\n`, "utf8");
  } catch (error) {
    if (debug) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`claudex: warning: failed to persist refreshed auth tokens: ${message}`);
    }
  }
}

async function refreshChatgptBearerToken(authState: AuthState, debug: boolean): Promise<string> {
  if (!authState.chatgptRefreshConfig) {
    throw new Error("chatgpt refresh config is missing");
  }
  if (authState.refreshInFlight) {
    return authState.refreshInFlight;
  }

  authState.refreshInFlight = (async () => {
    const refreshConfig = authState.chatgptRefreshConfig!;
    const response = await fetch("https://auth.openai.com/oauth/token", {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify({
        grant_type: "refresh_token",
        refresh_token: refreshConfig.refreshToken,
        client_id: refreshConfig.clientId,
      }),
    });

    const text = await response.text();
    if (!response.ok) {
      throw new Error(`token refresh failed with status ${response.status}: ${text.slice(0, 200)}`);
    }

    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch {
      throw new Error("token refresh returned non-JSON response");
    }

    const refreshedAccessToken =
      typeof parsed.access_token === "string" && parsed.access_token.trim().length > 0
        ? parsed.access_token.trim()
        : undefined;
    const refreshedIdToken =
      typeof parsed.id_token === "string" && parsed.id_token.trim().length > 0
        ? parsed.id_token.trim()
        : undefined;
    const refreshedRefreshToken =
      typeof parsed.refresh_token === "string" && parsed.refresh_token.trim().length > 0
        ? parsed.refresh_token.trim()
        : undefined;

    const nextBearerToken = refreshedAccessToken || refreshedIdToken;
    if (!nextBearerToken) {
      throw new Error("token refresh response did not include access_token or id_token");
    }

    authState.bearerToken = nextBearerToken;
    if (refreshedRefreshToken) {
      authState.chatgptRefreshConfig = {
        ...authState.chatgptRefreshConfig!,
        refreshToken: refreshedRefreshToken,
      };
    }

    persistRefreshedChatgptTokens(
      refreshConfig.authPath,
      {
        accessToken: refreshedAccessToken || authState.bearerToken,
        idToken: refreshedIdToken,
        refreshToken: refreshedRefreshToken,
      },
      debug
    );

    if (debug) {
      console.error("claudex: refreshed ChatGPT bearer token using refresh_token");
    }
    return authState.bearerToken;
  })().finally(() => {
    authState.refreshInFlight = undefined;
  });

  return authState.refreshInFlight;
}

async function proxyResponsesAsAnthropic(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  requestPath: string,
  upstreamOrigin: URL,
  authState: AuthState,
  overrideBody: JsonObject,
  options: ProxyOptions,
  allowRefreshRetry = true
): Promise<void> {
  const upstreamUrl = buildUpstreamUrl(
    upstreamOrigin,
    rewriteRequestPath(upstreamOrigin, requestPath, options.upstreamWireApi)
  );
  const upstreamPayload = JSON.stringify({
    ...overrideBody,
    stream: true,
  });

  const headers = {
    ...mergeRequestHeaders(req, authState),
    "content-type": "application/json",
    "content-length": String(Buffer.byteLength(upstreamPayload)),
  };

  const upstreamResponse = await fetch(upstreamUrl, {
    method: "POST",
    headers,
    body: upstreamPayload,
  });

  if (upstreamResponse.status === 401 && allowRefreshRetry && authState.chatgptRefreshConfig) {
    try {
      await refreshChatgptBearerToken(authState, options.debug);
      await proxyResponsesAsAnthropic(req, res, requestPath, upstreamOrigin, authState, overrideBody, options, false);
      return;
    } catch (error) {
      if (options.debug) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`claudex: token refresh attempt failed: ${message}`);
      }
    }
  }

  if (upstreamResponse.status >= 400) {
    const errorText = await upstreamResponse.text();
    res.writeHead(upstreamResponse.status, {
      "content-type": "application/json",
    });
    res.end(errorText);
    return;
  }

  if (!upstreamResponse.body) {
    writeJson(res, 502, {
      type: "error",
      error: { type: "api_error", message: "empty stream body from upstream" },
    });
    return;
  }

  const streamRequested = overrideBody.stream !== false;
  const responseId = `msg_${Date.now().toString(16)}`;
  let model = String(overrideBody.model || "");
  let text = "";
  let parsedContent: Array<Record<string, unknown>> = [];
  let stopReason: "tool_use" | "end_turn" = "end_turn";
  let usageInputTokens = 0;
  let usageOutputTokens = 0;

  const decoder = new TextDecoder();
  let buffered = "";
  for await (const chunk of Readable.fromWeb(upstreamResponse.body as any)) {
    buffered = parseSseEvents(buffered + decoder.decode(chunk as Buffer, { stream: true }), (_eventName, parsed) => {
      if (parsed?.type === "response.created" && parsed?.response?.model) {
        model = String(parsed.response.model);
      }
      if (parsed?.type === "response.output_text.delta" && typeof parsed.delta === "string") {
        text += parsed.delta;
      }
      if (parsed?.type === "response.completed") {
        usageInputTokens = Number(parsed?.response?.usage?.input_tokens || 0);
        usageOutputTokens = Number(parsed?.response?.usage?.output_tokens || 0);
        if (typeof parsed?.response?.model === "string" && parsed.response.model.trim().length > 0) {
          model = parsed.response.model;
        }
        if (Array.isArray(parsed?.response?.output)) {
          const mapped = mapResponsesOutputToAnthropicContent(parsed.response.output);
          parsedContent = mapped.content;
          stopReason = mapped.stopReason;
        }
      }
    });
  }

  if (parsedContent.length === 0 && text.length > 0) {
    parsedContent = [{ type: "text", text }];
  }

  if (streamRequested) {
    res.writeHead(200, {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache",
      connection: "keep-alive",
    });

    writeSseEvent(res, "message_start", {
      type: "message_start",
      message: {
        id: responseId,
        type: "message",
        role: "assistant",
        model,
        content: [],
        stop_reason: null,
        stop_sequence: null,
        usage: { input_tokens: 0, output_tokens: 0 },
      },
    });

    for (let i = 0; i < parsedContent.length; i += 1) {
      const block = parsedContent[i];
      if (block.type === "text") {
        writeSseEvent(res, "content_block_start", {
          type: "content_block_start",
          index: i,
          content_block: { type: "text", text: "" },
        });
        writeSseEvent(res, "content_block_delta", {
          type: "content_block_delta",
          index: i,
          delta: { type: "text_delta", text: block.text || "" },
        });
        writeSseEvent(res, "content_block_stop", {
          type: "content_block_stop",
          index: i,
        });
      } else if (block.type === "tool_use") {
        writeSseEvent(res, "content_block_start", {
          type: "content_block_start",
          index: i,
          content_block: {
            type: "tool_use",
            id: block.id,
            name: block.name,
            input: {},
          },
        });
        writeSseEvent(res, "content_block_delta", {
          type: "content_block_delta",
          index: i,
          delta: {
            type: "input_json_delta",
            partial_json: JSON.stringify(block.input ?? {}),
          },
        });
        writeSseEvent(res, "content_block_stop", {
          type: "content_block_stop",
          index: i,
        });
      }
    }

    writeSseEvent(res, "message_delta", {
      type: "message_delta",
      delta: { stop_reason: stopReason, stop_sequence: null },
      usage: { output_tokens: usageOutputTokens },
    });
    writeSseEvent(res, "message_stop", { type: "message_stop" });
    res.end();
    return;
  }

  const body = JSON.stringify({
    id: responseId,
    type: "message",
    role: "assistant",
    model,
    content: parsedContent,
    stop_reason: stopReason,
    stop_sequence: null,
    usage: { input_tokens: usageInputTokens, output_tokens: usageOutputTokens },
  });

  res.writeHead(200, {
    "content-type": "application/json",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

async function proxyRaw(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  bodyBuffer: Buffer,
  requestPath: string,
  upstreamOrigin: URL,
  authState: AuthState,
  options: ProxyOptions,
  overrideBody: JsonObject | null = null,
  allowRefreshRetry = true
): Promise<void> {
  const headers = mergeRequestHeaders(req, authState);

  let outboundBody = bodyBuffer;
  if (overrideBody !== null) {
    const payload = JSON.stringify(overrideBody);
    outboundBody = Buffer.from(payload);
    headers["content-type"] = "application/json";
    headers["content-length"] = String(outboundBody.length);
  } else if (outboundBody.length > 0) {
    headers["content-length"] = String(outboundBody.length);
  }

  const upstreamUrl = buildUpstreamUrl(
    upstreamOrigin,
    rewriteRequestPath(upstreamOrigin, requestPath, options.upstreamWireApi)
  );
  const upstreamResponse = await fetch(upstreamUrl, {
    method: req.method,
    headers,
    body: req.method === "GET" || req.method === "HEAD" ? undefined : outboundBody,
  });

  if (upstreamResponse.status === 401 && allowRefreshRetry && authState.chatgptRefreshConfig) {
    try {
      await refreshChatgptBearerToken(authState, options.debug);
      await proxyRaw(req, res, bodyBuffer, requestPath, upstreamOrigin, authState, options, overrideBody, false);
      return;
    } catch (error) {
      if (options.debug) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`claudex: token refresh attempt failed: ${message}`);
      }
    }
  }

  res.writeHead(upstreamResponse.status, copyHeadersFromUpstream(upstreamResponse.headers));
  if (!upstreamResponse.body) {
    res.end();
    return;
  }

  Readable.fromWeb(upstreamResponse.body as any).pipe(res);
}

export async function startProxy(
  listenHost: string,
  listenPort: number,
  upstreamOrigin: URL,
  authState: AuthState,
  options: ProxyOptions
): Promise<http.Server> {
  const server = http.createServer(async (req, res) => {
    try {
      const url = new URL(req.url || "/", `http://${listenHost}:${listenPort}`);
      const path = url.pathname;
      const method = req.method || "GET";

      if (method === "GET" && path === "/health") {
        writeJson(res, 200, {
          ok: true,
          forced_model: options.forcedModel,
          upstream: upstreamOrigin.origin + upstreamOrigin.pathname,
          wire_api: options.upstreamWireApi,
        });
        return;
      }

      if (method === "GET" && path === "/v1/models") {
        writeJson(res, 200, {
          object: "list",
          data: [
            {
              id: options.forcedModel,
              object: "model",
              created: Math.floor(Date.now() / 1000),
              owned_by: "claudex",
            },
          ],
        });
        return;
      }

      if (method === "GET" && path.startsWith("/v1/models/")) {
        const requestedModel = decodeURIComponent(path.slice("/v1/models/".length));
        writeJson(res, 200, {
          id: requestedModel,
          object: "model",
          created: Math.floor(Date.now() / 1000),
          owned_by: "claudex",
        });
        return;
      }

      if (method === "POST" && path === "/v1/messages/count_tokens") {
        const bodyBuffer = await readBody(req);
        let parsed: JsonObject = {};
        try {
          parsed = bodyBuffer.length > 0 ? JSON.parse(bodyBuffer.toString("utf8")) : {};
        } catch {
          parsed = {};
        }
        writeJson(res, 200, { input_tokens: approxTokenCount(parsed) });
        return;
      }

      if (method === "POST" && path === "/v1/messages") {
        const bodyBuffer = await readBody(req);
        let parsed: JsonObject;
        try {
          parsed = bodyBuffer.length > 0 ? JSON.parse(bodyBuffer.toString("utf8")) : {};
        } catch {
          writeJson(res, 400, {
            type: "error",
            error: {
              type: "invalid_request_error",
              message: "Invalid JSON body",
            },
          });
          return;
        }

        const originalModel = String(parsed.model ?? "");
        parsed.model = options.forcedModel;
        applyDefaultEffort(parsed, {
          forcedModel: options.forcedModel,
          defaultReasoningEffort: options.defaultReasoningEffort,
          preserveClientEffort: options.preserveClientEffort,
        });
        const removedToolFields = sanitizeToolFields(parsed);
        let removedRequestFields = 0;

        if (options.upstreamWireApi === "responses") {
          removedRequestFields = sanitizeUnsupportedRequestFields(parsed);
        }

        if (options.debug) {
          const effort = parsed.output_config?.effort ?? parsed.reasoning?.effort ?? "unset";
          console.error(
            `claudex-proxy model remap: ${originalModel} -> ${options.forcedModel}, effort=${effort}, wire_api=${options.upstreamWireApi}, safe_mode=${options.safeMode}, preserve_client_effort=${options.preserveClientEffort}, removed_request_fields=${removedRequestFields}, removed_tool_fields=${removedToolFields}`
          );
        }

        if (options.upstreamWireApi === "responses") {
          await proxyResponsesAsAnthropic(
            req,
            res,
            url.pathname + url.search,
            upstreamOrigin,
            authState,
            adaptAnthropicMessagesRequestForResponses(parsed, options),
            options
          );
          return;
        }

        await proxyRaw(req, res, bodyBuffer, url.pathname + url.search, upstreamOrigin, authState, options, parsed);
        return;
      }

      const bodyBuffer = await readBody(req);
      await proxyRaw(req, res, bodyBuffer, url.pathname + url.search, upstreamOrigin, authState, options);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      writeJson(res, 500, {
        type: "error",
        error: {
          type: "api_error",
          message: `claudex-proxy internal error: ${message}`,
        },
      });
    }
  });

  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(listenPort, listenHost, () => resolve());
  });

  return server;
}

export { adaptAnthropicMessagesRequestForResponses };
